# Site settings
title: the generator files
description: >
  This is a small blog where you'll find some descriptions of my code,
  random programming or installation quirks, science, opinions and
  occasionally some art.
baseurl: ""
url: "https://jdcapa.github.io"
github_username:  jdcapa
markdown: kramdown
noindex: true
